Added some bean overrides for native compilation
AxonFramework/extension-spring-aot pull request #99
Opened 2023-09-04 10:05 UTC by abuijze

Some default beans aren't compatible with Spring AOT when compiled to native. The resourceInjector now defaults to the ConfigurationResourceInjector, as it will also automatically consider Spring Beans as resources.

2023-09-04 10:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AxonFramework/extension-spring-aot?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AxonFramework/extension-spring-aot?pullRequest=99) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AxonFramework/extension-spring-aot?pullRequest=99) it.</sub>

2023-09-04 11:19 UTC, smcvb requested changes
Conceptually this looks fine, but there are some minor missers present in this PR that we need to resolve.

2023-09-04 11:19 UTC, smcvb commented on src/main/java/org/axonframework/springboot/aot/autoconfig/ResourceInjectorAutoConfiguration.java
> +package org.axonframework.springboot.aot.autoconfig;
I'm missing the copyright notice and a little class-level JavaDoc.

2023-09-04 11:19 UTC, smcvb commented on src/test/java/org/axonframework/springboot/aot/autoconfig/ResourceInjectorAutoConfigurationTest.java
> + * Tests the {@link SimpleEntityManagerProviderAutoConfiguration} providing a {@link SimpleEntityManagerProvider}.
The JavaDoc doesn't really  match the test class I think.

2023-09-04 11:19 UTC, smcvb commented on src/test/java/org/axonframework/springboot/aot/autoconfig/ResourceInjectorAutoConfigurationTest.java
> +    void defaultContextResolverIsPresent() {
```suggestion
    void defaultResourceInjectorIsPresent() {
```

2023-09-05 07:19 UTC, gklijs requested changes
One additional suggestion. Otherwise looks good.

2023-09-05 07:19 UTC, gklijs commented on src/test/java/org/axonframework/springboot/aot/autoconfig/ResourceInjectorAutoConfigurationTest.java
> + * @author Gerard Klijs
```suggestion
 * @author Allard Buijze
```

2023-09-08 10:08 UTC, smcvb approved these changes
Looks good to me :+1:

2023-09-12 13:42 UTC, merged